const mongoose=require('mongoose');
const ProfileSchema=mongoose.Schema({
    patientuser:{
		type:mongoose.Schema.Types.ObjectId,
		ref:'patientuser'
    },
    myReport:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"myreport"
    }],
    name:{
		type:String,
		required:true
    },
    age:{
        type:String,
        required:true
    },
    avatar:{
        type:String,
    },
	email:{
		type:String,
		required:true,
		unique:true
    },
    address:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true
    },
    emergencyPhone:{
        type:String,
        required:true
    },
    RecordId:{
        type:String,
        unique:true
    },
	date:{
	type:Date,
	default: Date.now
}
});
module.exports=mongoose.model('profile',ProfileSchema);